id: P000500
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS18339
  title: གསུང་འབུམ། བློ་གྲོས་རྒྱ་མཚོ།
  author: ''
  volumes:
    d100228c72714cafa8c5b3ea67d9bbdb:
      image_group_id: I8LS18344
      title: Volume 1 of gsung 'bum/ blo gros rgya mtsho/
      volume_number: 1
      total_pages: 560
      base_file: v001.txt
